#!/usr/bin/env python3
"""Generates core/jni/jni_slots.inc from third_party/jni/jni.h.

Every slot of the JNIEnv function table lands in exactly one list, in
table order, so the bridge never hardcodes slot numbers:
  JNI_AUTO(index, Name)                 plain C signature: marshalled by template
  JNI_CALL(index, Name, target, form, ret)
      Call*Method / CallNonvirtual*Method / CallStatic*Method / NewObject
      target: 'i' instance, 'n' nonvirtual, 's' static, 'o' NewObject
      form: 0 = C varargs, 1 = va_list (V), 2 = jvalue array (A)
      ret: JNI type char of the return value
  JNI_MANUAL(index, Name)               hand-written in jni_bridge.cpp
  JNI_NONE(index, Name)                 reserved / unsupported
"""
import re, sys, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
src = (root / "third_party/jni/jni.h").read_text()
body = re.search(r"struct JNINativeInterface \{(.*?)\n\};", src, re.S).group(1)
body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
MANUAL = re.compile(r"^(GetMethodID|GetStaticMethodID|GetStringU?T?F?Chars|ReleaseStringU?T?F?Chars|"
                    r"GetStringCritical|ReleaseStringCritical|Get\w+ArrayElements|Release\w+ArrayElements|"
                    r"GetPrimitiveArrayCritical|ReleasePrimitiveArrayCritical|RegisterNatives|GetJavaVM|"
                    r"NewGlobalRef|NewWeakGlobalRef|DeleteLocalRef|DeleteGlobalRef|DeleteWeakGlobalRef)$")
NONE = re.compile(r"^(reserved\d+|DefineClass)$")
CALL = re.compile(r"^(CallNonvirtual|CallStatic|Call)(Object|Boolean|Byte|Char|Short|Int|Long|Float|Double|Void)Method([VA]?)$")
RET = dict(Object="L", Boolean="Z", Byte="B", Char="C", Short="S", Int="I", Long="J", Float="F", Double="D", Void="V")
TARGET = {"Call": "i", "CallNonvirtual": "n", "CallStatic": "s"}
FORM = {"": 0, "V": 1, "A": 2}

def classify(idx, name, args):
    if NONE.match(name):
        return f"JNI_NONE({idx}, {name})"
    m = CALL.match(name)
    if m:
        return f"JNI_CALL({idx}, {name}, '{TARGET[m.group(1)]}', {FORM[m.group(3)]}, '{RET[m.group(2)]}')"
    m = re.match(r"^NewObject([VA]?)$", name)
    if m:
        return f"JNI_CALL({idx}, {name}, 'o', {FORM[m.group(1)]}, 'L')"
    if MANUAL.match(name):
        return f"JNI_MANUAL({idx}, {name})"
    if "..." in args or "va_list" in args or "jvalue" in args:
        sys.exit(f"{name}: variadic slot with no handler category")
    return f"JNI_AUTO({idx}, {name})"

out = ["// Generated by tools/gen_jni_slots.py — do not edit."]
idx = 0
for decl in body.split(";"):
    decl = " ".join(decl.split())
    if not decl:
        continue
    if decl.startswith("void*") and "(" not in decl:  # reservedN
        out.append(classify(idx, f"reserved{idx}", ""))
    else:
        m = re.search(r"\(\*(\w+)\)\((.*)\)$", decl)
        if not m:
            sys.exit(f"cannot parse: {decl}")
        out.append(classify(idx, m.group(1), m.group(2)))
    idx += 1
(root / "core/jni/jni_slots.inc").write_text("\n".join(out) + "\n")
print(f"{idx} slots")
